config/routes.rb
PhotoAlbum20130319::Application.routes.draw do
  root :to => 'welcome#index'

  resources :albums, :only => [:new, :create, :show, :filter] do
    member do
      get :filter
    end
  end

  resources :photos, :only => [:new, :create]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
  attr_accessible :name
  has_many :photos
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  url        :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  album_id   :integer
#

class Photo < ActiveRecord::Base
  attr_accessible :name, :url, :remote_url_url
  belongs_to :album
  mount_uploader :url, PicUploader
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @album = Album.new
  end

  def create
    @album = Album.create( params[:album] )
  end

  def show
    @album = Album.find( params[:id] )
    @photos = @album.photos
  end

  def filter
    album = Album.find( params[:id] )
    @photos = album.photos.limit( params[:count] )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authentication

  private
  def authentication
    @auth = User.find( session[:user_id] ) if session[:user_id].present?
  end

  def logged_in
    session[:user_id].present?

  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
    @album = Album.find(params[:album_id])
    @photo = Photo.new
  end

  def create
    album = Album.find( params[:album_id] )
    album.photos << Photo.create( params[:photo] )
    @photos = album.photos
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.where( :username => params[:username] ).first

    if user.present? && user.authenticate( params[:password] )
      session[:user_id] = user.id
    else
      session[:user_id] = nil
    end

    authentication
  end

  def destroy
    session[:user_id] = nil
    @auth = nil
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.haml
.row
  .large-6.columns.large-centered
    = form_for @album, :remote => true do |f|
      = f.label :name
      = f.text_field :name
      = f.submit
      = link_to('Cancel', '#', remote: true, :'data-clear-form' => true)

app/views/albums/_index.html.haml
- if Album.all.count > 0
  - Album.order(:name).each do |album|
    %p.album
      = link_to(album.name, album)
      = album.photos.count

app/views/albums/create.js.erb
$('#new').empty();
$('.albums').empty().append('<%=j render partial: 'index' %>');

app/views/albums/filter.js.erb
$('#new').empty();
$('.photos').empty().append('<%=j render partial: 'photos/index' %>');

app/views/albums/new.js.erb
$('#new').empty().append('<%=j render partial: 'form' %>');

app/views/albums/show.html.haml
.row
  .large-12.columns
    %h3= "#{@album.name} Album"
    .row
      .large-4.columns.large-centered{ :style => 'text-align:center;' }
        = link_to("New Photo", new_photo_path(:album_id => params[:id]), remote: true, :class => 'button secondary')
        #slider{ :'data-album-id' => @album.id }

    #photo-form
    .photos
      = render partial: 'photos/index'

app/views/layouts/_footer.html.erb
<!-- Footer -->

<footer class="row">
  <div class="large-12 columns">
    <hr />
    <div class="row">
      <div class="large-6 columns">
        <p>&copy; Copyright phtlbm & lulz.</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="#">About</a></li>
          <li><a href="#">FAQ</a></li>
          <li><a href="#">Contact</a></li>
          <li><a href="#">Careers</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><%= link_to("phtlbm", root_path) %></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
<!--     <ul class="left">
      <li class="divider"></li>
      <li><%#= link_to("Exercises", root_path ) %>
      <li class="divider"></li>
      <li><%#= link_to("Graphs", '#') %>
      <li class="divider"></li>
    </ul> -->

    <!-- Right Nav Section -->
    <ul class="right">
      <% if @auth %>
      <li class="divider"></li>
      <li><%= link_to("Profile", edit_subscriber_path(@auth.sub) ) %>
      <li class="divider"></li>
      <li><%= link_to("#{ @auth.username }", '#' ) %>
      <li class="divider"></li>
      <li><%= link_to("Logout", login_path, :method => 'delete', :remote => true ) %>
      <li class="divider"></li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flirt</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="nav-wrap">
  <%= render :partial => 'layouts/nav' %>
</div>

<%= yield %>

<%= render :partial => 'layouts/footer' %>

  <!-- this gives you the name of the page you're on. Magic. -->


</body>
</html>

app/views/photos/_form.html.haml
.row
  .large-6.columns.large-centered
    = form_for @photo, :html => {:multipart => true}, :remote => true do |f|
      // ADD MULTIPART WHEN YOU'RE ADDING ANY KIND OF FILE
      = f.label :name
      = f.text_field :name
      = f.label :url
      = f.file_field :url
      = f.text_field :remote_url_url # THIS SYNTAX IS IMPORTANT
      = hidden_field_tag :album_id, params[:album_id]
      = f.submit
      = link_to('Cancel', '#', remote: true, :'data-clear-form' => true)

app/views/photos/_index.html.haml
- if @photos
  %ul
    - @photos.each do |photo|
      %li= image_tag(photo.url.thumb)

app/views/photos/create.js.erb
$('#photo-form').empty();
$('.photos').empty().append('<%=j render :partial => 'index' %>');

app/views/photos/new.js.erb
$('#photo-form').empty().append('<%=j render partial: 'form' %>');

app/views/session/_display.js.erb
$('.nav-wrap').empty().append('<%=j render :partial => 'layouts/nav' %>');
$('.content').empty().prepend('<%=j render :partial => 'subscriptions/index' %>');

app/views/session/_form.html.haml
.row
  .large-8.columns.large-centered
    = form_tag( login_path, :remote => true ) do
      = label_tag 'Username'
      = text_field_tag 'username'
      = label_tag 'Password'
      = password_field_tag 'password'
      = submit_tag "Go Flirt", :class => 'button success'
      = link_to('Cancel', '#', :'data-clear-form' => true, :class => 'button right')

app/views/session/create.js.erb
<% if session[:user_id].present? %>
  $('.sign-in-links').empty();
  $('#new').empty();
  <%= render :partial => 'display' %>
<% else %>
  $('#new').empty();
  $('#new').append('<%=j render :partial => 'form' %>');
<% end %>

app/views/session/destroy.js.erb
$('.sign-in-links').empty();
$('.sign-in-links').append('<%=j render :partial => 'welcome/sign_in_links' %>');
<%= render :partial => 'display' %>

app/views/session/new.js.erb
$('#new').empty();
$('#new').append('<%=j render :partial => 'form' %>');

app/views/shared/_errors.html.haml
- if @user.errors.any?
  .alert-box.alert
    = "#{pluralize(@user.errors.count, 'error')} in this form:"
    - @user.errors.full_messages.each do |error|
      %br= error

app/views/welcome/_sign_in_links.html.haml
- if @auth.nil?
  = link_to( 'Register', new_subscriber_path, :remote => true, :class => 'button' )
  = link_to( 'Login', login_path, :remote => true, :class => 'button' )

app/views/welcome/index.html.haml
.row
  .large-6.columns
    %h1 Welcome to <span>phtlbm</span>!
    = link_to("New Album", new_album_path, :remote => true)
    #new
  .large-6.columns.albums
    = render partial: 'albums/index'

app/views/welcome/purchase.js.erb
$('.nav-wrap').empty().append('<%=j render :partial => 'layouts/nav' %>');
$('.content').empty().prepend('<%=j render :partial => 'subscriptions/index' %>');